# Generated by Django 5.2.6 on 2025-10-01 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userregistration',
            name='date_registration',
            field=models.DateField(auto_now_add=True),
        ),
    ]
